// Code generated by the Encore 1.49.1 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:9400"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly analytics: analytics.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly fitness: fitness.ServiceClient
    public readonly nutrition: nutrition.ServiceClient
    public readonly users: users.ServiceClient
    public readonly workouts: workouts.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.analytics = new analytics.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.fitness = new fitness.ServiceClient(base)
        this.nutrition = new nutrition.ServiceClient(base)
        this.users = new users.ServiceClient(base)
        this.workouts = new workouts.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getNutritionStats as api_analytics_nutrition_stats_getNutritionStats } from "~backend/analytics/nutrition_stats";
import { getWorkoutStats as api_analytics_workout_stats_getWorkoutStats } from "~backend/analytics/workout_stats";

export namespace analytics {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getNutritionStats = this.getNutritionStats.bind(this)
            this.getWorkoutStats = this.getWorkoutStats.bind(this)
        }

        /**
         * Retrieves nutrition statistics for the authenticated user.
         */
        public async getNutritionStats(params: RequestType<typeof api_analytics_nutrition_stats_getNutritionStats>): Promise<ResponseType<typeof api_analytics_nutrition_stats_getNutritionStats>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                days: params.days === undefined ? undefined : String(params.days),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/nutrition`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_nutrition_stats_getNutritionStats>
        }

        /**
         * Retrieves workout statistics for the authenticated user.
         */
        public async getWorkoutStats(params: RequestType<typeof api_analytics_workout_stats_getWorkoutStats>): Promise<ResponseType<typeof api_analytics_workout_stats_getWorkoutStats>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                days: params.days === undefined ? undefined : String(params.days),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics/workouts`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_analytics_workout_stats_getWorkoutStats>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { login as api_auth_login_login } from "~backend/auth/login";
import { signup as api_auth_signup_signup } from "~backend/auth/signup";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.login = this.login.bind(this)
            this.signup = this.signup.bind(this)
        }

        /**
         * Logs in a user with email and password.
         */
        public async login(params: RequestType<typeof api_auth_login_login>): Promise<ResponseType<typeof api_auth_login_login>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/login`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_login_login>
        }

        /**
         * Creates a new user account.
         */
        public async signup(params: RequestType<typeof api_auth_signup_signup>): Promise<ResponseType<typeof api_auth_signup_signup>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/auth/signup`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_signup_signup>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { addNutrition as api_fitness_add_nutrition_addNutrition } from "~backend/fitness/add_nutrition";
import { addProgress as api_fitness_add_progress_addProgress } from "~backend/fitness/add_progress";
import { createWorkout as api_fitness_create_workout_createWorkout } from "~backend/fitness/create_workout";
import { getAnalytics as api_fitness_get_analytics_getAnalytics } from "~backend/fitness/get_analytics";
import { getWorkout as api_fitness_get_workout_getWorkout } from "~backend/fitness/get_workout";
import { listExercises as api_fitness_list_exercises_listExercises } from "~backend/fitness/list_exercises";
import { listNutrition as api_fitness_list_nutrition_listNutrition } from "~backend/fitness/list_nutrition";
import { listProgress as api_fitness_list_progress_listProgress } from "~backend/fitness/list_progress";
import { listWorkoutLogs as api_fitness_list_workout_logs_listWorkoutLogs } from "~backend/fitness/list_workout_logs";
import { listWorkouts as api_fitness_list_workouts_listWorkouts } from "~backend/fitness/list_workouts";
import { logWorkout as api_fitness_log_workout_logWorkout } from "~backend/fitness/log_workout";

export namespace fitness {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addNutrition = this.addNutrition.bind(this)
            this.addProgress = this.addProgress.bind(this)
            this.createWorkout = this.createWorkout.bind(this)
            this.getAnalytics = this.getAnalytics.bind(this)
            this.getWorkout = this.getWorkout.bind(this)
            this.listExercises = this.listExercises.bind(this)
            this.listNutrition = this.listNutrition.bind(this)
            this.listProgress = this.listProgress.bind(this)
            this.listWorkoutLogs = this.listWorkoutLogs.bind(this)
            this.listWorkouts = this.listWorkouts.bind(this)
            this.logWorkout = this.logWorkout.bind(this)
        }

        /**
         * Logs a nutrition entry for a specific meal.
         */
        public async addNutrition(params: RequestType<typeof api_fitness_add_nutrition_addNutrition>): Promise<ResponseType<typeof api_fitness_add_nutrition_addNutrition>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nutrition`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_add_nutrition_addNutrition>
        }

        /**
         * Records a progress measurement like weight, body fat percentage, or body measurements.
         */
        public async addProgress(params: RequestType<typeof api_fitness_add_progress_addProgress>): Promise<ResponseType<typeof api_fitness_add_progress_addProgress>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/progress`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_add_progress_addProgress>
        }

        /**
         * Creates a new workout routine with exercises.
         */
        public async createWorkout(params: RequestType<typeof api_fitness_create_workout_createWorkout>): Promise<ResponseType<typeof api_fitness_create_workout_createWorkout>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workouts`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_create_workout_createWorkout>
        }

        /**
         * Provides comprehensive analytics and statistics for fitness progress.
         */
        public async getAnalytics(): Promise<ResponseType<typeof api_fitness_get_analytics_getAnalytics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analytics`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_get_analytics_getAnalytics>
        }

        /**
         * Retrieves a specific workout routine with all its exercises.
         */
        public async getWorkout(params: { id: number }): Promise<ResponseType<typeof api_fitness_get_workout_getWorkout>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workouts/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_get_workout_getWorkout>
        }

        /**
         * Retrieves all available exercises.
         */
        public async listExercises(): Promise<ResponseType<typeof api_fitness_list_exercises_listExercises>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/exercises`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_list_exercises_listExercises>
        }

        /**
         * Retrieves nutrition logs for a specific date with daily totals.
         */
        public async listNutrition(params: RequestType<typeof api_fitness_list_nutrition_listNutrition>): Promise<ResponseType<typeof api_fitness_list_nutrition_listNutrition>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                date: params.date,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nutrition`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_list_nutrition_listNutrition>
        }

        /**
         * Retrieves all progress measurements ordered by date.
         */
        public async listProgress(): Promise<ResponseType<typeof api_fitness_list_progress_listProgress>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/progress`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_list_progress_listProgress>
        }

        /**
         * Retrieves all workout logs with exercise details.
         */
        public async listWorkoutLogs(): Promise<ResponseType<typeof api_fitness_list_workout_logs_listWorkoutLogs>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workout-logs`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_list_workout_logs_listWorkoutLogs>
        }

        /**
         * Retrieves all workout routines with optional filtering by category or difficulty.
         */
        public async listWorkouts(): Promise<ResponseType<typeof api_fitness_list_workouts_listWorkouts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workouts`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_list_workouts_listWorkouts>
        }

        /**
         * Logs a completed workout session.
         */
        public async logWorkout(params: RequestType<typeof api_fitness_log_workout_logWorkout>): Promise<ResponseType<typeof api_fitness_log_workout_logWorkout>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workout-logs`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_fitness_log_workout_logWorkout>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getDailyLogs as api_nutrition_get_daily_logs_getDailyLogs } from "~backend/nutrition/get_daily_logs";
import { logFood as api_nutrition_log_food_logFood } from "~backend/nutrition/log_food";
import { searchFoods as api_nutrition_search_foods_searchFoods } from "~backend/nutrition/search_foods";

export namespace nutrition {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getDailyLogs = this.getDailyLogs.bind(this)
            this.logFood = this.logFood.bind(this)
            this.searchFoods = this.searchFoods.bind(this)
        }

        /**
         * Retrieves nutrition logs for a specific date for the authenticated user.
         */
        public async getDailyLogs(params: { date: string }): Promise<ResponseType<typeof api_nutrition_get_daily_logs_getDailyLogs>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nutrition/logs/${encodeURIComponent(params.date)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nutrition_get_daily_logs_getDailyLogs>
        }

        /**
         * Logs a food item for the authenticated user.
         */
        public async logFood(params: RequestType<typeof api_nutrition_log_food_logFood>): Promise<ResponseType<typeof api_nutrition_log_food_logFood>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nutrition/logs`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nutrition_log_food_logFood>
        }

        /**
         * Searches for foods by name.
         */
        public async searchFoods(params: RequestType<typeof api_nutrition_search_foods_searchFoods>): Promise<ResponseType<typeof api_nutrition_search_foods_searchFoods>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                query: params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/nutrition/foods/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_nutrition_search_foods_searchFoods>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_users_create_create } from "~backend/users/create";
import { get as api_users_get_get } from "~backend/users/get";

export namespace users {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
        }

        /**
         * Creates a new user profile.
         */
        public async create(params: RequestType<typeof api_users_create_create>): Promise<ResponseType<typeof api_users_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_create_create>
        }

        /**
         * Retrieves the current user's profile.
         */
        public async get(): Promise<ResponseType<typeof api_users_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/me`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_users_get_get>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createTemplate as api_workouts_create_template_createTemplate } from "~backend/workouts/create_template";
import { listExercises as api_workouts_list_exercises_listExercises } from "~backend/workouts/list_exercises";
import { listSessions as api_workouts_list_sessions_listSessions } from "~backend/workouts/list_sessions";
import { listTemplates as api_workouts_list_templates_listTemplates } from "~backend/workouts/list_templates";
import { startSession as api_workouts_start_session_startSession } from "~backend/workouts/start_session";

export namespace workouts {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createTemplate = this.createTemplate.bind(this)
            this.listExercises = this.listExercises.bind(this)
            this.listSessions = this.listSessions.bind(this)
            this.listTemplates = this.listTemplates.bind(this)
            this.startSession = this.startSession.bind(this)
        }

        /**
         * Creates a new workout template for the authenticated user.
         */
        public async createTemplate(params: RequestType<typeof api_workouts_create_template_createTemplate>): Promise<ResponseType<typeof api_workouts_create_template_createTemplate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workouts/templates`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_workouts_create_template_createTemplate>
        }

        /**
         * Retrieves all available exercises.
         */
        public async listExercises(): Promise<ResponseType<typeof api_workouts_list_exercises_listExercises>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workouts/exercises`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_workouts_list_exercises_listExercises>
        }

        /**
         * Retrieves all workout sessions for the authenticated user.
         */
        public async listSessions(): Promise<ResponseType<typeof api_workouts_list_sessions_listSessions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workouts/sessions`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_workouts_list_sessions_listSessions>
        }

        /**
         * Retrieves all workout templates for the authenticated user.
         */
        public async listTemplates(): Promise<ResponseType<typeof api_workouts_list_templates_listTemplates>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workouts/templates`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_workouts_list_templates_listTemplates>
        }

        /**
         * Starts a new workout session for the authenticated user.
         */
        public async startSession(params: RequestType<typeof api_workouts_start_session_startSession>): Promise<ResponseType<typeof api_workouts_start_session_startSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/workouts/sessions`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_workouts_start_session_startSession>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.49.1)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
